/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import projetbdm.*;

/**
 *
 * @author cmolin
 */
public class WindowAdmin extends javax.swing.JFrame {
    
    private final Connection con;

    /**
     * Creates new form WindowAdmin
     * @param con
     */
    public WindowAdmin(Connection con) {
        this.con = con;
        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jButtonAddSysteme = new javax.swing.JButton();
        jLabelErrSysteme = new javax.swing.JLabel();
        jLabelSuccSysteme = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPaneImage = new javax.swing.JTabbedPane();
        jPanelSysteme = new javax.swing.JPanel();
        jPanelUtilisateur = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButtonAddImage = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneImage = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelAddImage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomI = new javax.swing.JTextField();
        jTextFieldDateI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescriptionI = new javax.swing.JTextArea();
        jButtonAnnulerImage = new javax.swing.JButton();
        jButtonSaveImage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUrlI = new javax.swing.JTextField();
        jButtonParcourirI = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un système"));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel4.setLayout(jPanel4Layout);

        jButtonAddSysteme.setText("Sauvegarder");
        jButtonAddSysteme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSystemeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jButtonAddSysteme, gridBagConstraints);

        jLabelErrSysteme.setForeground(new java.awt.Color(255, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel4.add(jLabelErrSysteme, gridBagConstraints);

        jLabelSuccSysteme.setForeground(new java.awt.Color(18, 224, 5));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel4.add(jLabelSuccSysteme, gridBagConstraints);

        jLabel6.setText("Nom système d'exploitation : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel4.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel4.add(jTextField1, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(790, 479));
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jTabbedPaneImage.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanelSysteme.setLayout(new java.awt.GridLayout(1, 0));
        jTabbedPaneImage.addTab("Système", jPanelSysteme);

        jPanelUtilisateur.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanelUtilisateurComponentShown(evt);
            }
        });
        jPanelUtilisateur.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanelUtilisateurFocusGained(evt);
            }
        });
        jPanelUtilisateur.setLayout(new java.awt.GridLayout(1, 0));
        jPanelUtilisateur.add(jPanel5);

        jTabbedPaneImage.addTab("Utilisateur", jPanelUtilisateur);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jToggleButtonAddImage.setText("Ajouter une image");
        jToggleButtonAddImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAddImageActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButtonAddImage, new java.awt.GridBagConstraints());

        jPanel2.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPaneImage.setViewportView(jTable1);

        jPanel2.add(jScrollPaneImage, "card2");

        jPanelAddImage.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter une image"));
        java.awt.GridBagLayout jPanelAddImageLayout = new java.awt.GridBagLayout();
        jPanelAddImageLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanelAddImageLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanelAddImage.setLayout(jPanelAddImageLayout);

        jLabel1.setText("Nom image : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelAddImage.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Date : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanelAddImage.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Description : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanelAddImage.add(jLabel3, gridBagConstraints);

        jTextFieldNomI.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanelAddImage.add(jTextFieldNomI, gridBagConstraints);

        jTextFieldDateI.setText("jTextField3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanelAddImage.add(jTextFieldDateI, gridBagConstraints);

        jTextAreaDescriptionI.setColumns(20);
        jTextAreaDescriptionI.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescriptionI);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        jPanelAddImage.add(jScrollPane1, gridBagConstraints);

        jButtonAnnulerImage.setText("Annuler");
        jButtonAnnulerImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        jPanelAddImage.add(jButtonAnnulerImage, gridBagConstraints);

        jButtonSaveImage.setText("Sauvegarder");
        jButtonSaveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        jPanelAddImage.add(jButtonSaveImage, gridBagConstraints);

        jLabel4.setText("Image : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanelAddImage.add(jLabel4, gridBagConstraints);

        jTextFieldUrlI.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanelAddImage.add(jTextFieldUrlI, gridBagConstraints);

        jButtonParcourirI.setText("Parcourir");
        jButtonParcourirI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcourirIActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanelAddImage.add(jButtonParcourirI, gridBagConstraints);

        jPanel2.add(jPanelAddImage, "card3");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPaneImage.addTab("Image", jPanel6);

        getContentPane().add(jTabbedPaneImage);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelUtilisateurFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanelUtilisateurFocusGained

    }//GEN-LAST:event_jPanelUtilisateurFocusGained

    private void jPanelUtilisateurComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelUtilisateurComponentShown
        /*Utilisateur u = new Utilisateur();
        try {
            java.util.Map maMap = con.getTypeMap();
            maMap.put("CM429363.UTILISATEUR_TYPE", Class.forName("projetbdm.Utilisateur"));
            PreparedStatement st = con.prepareStatement("select value(u) from utilisateur u");
            ResultSet rst = st.executeQuery();
            while (rst.next()) {
                u = (Utilisateur) rst.getObject(1, maMap);
                this.jComboBoxDeleteUtilisateur.addItem(u.login);
            }
        }
        catch(SQLException | ClassNotFoundException e) {
            System.out.println(e);
        }*/
    }//GEN-LAST:event_jPanelUtilisateurComponentShown

    private void jButtonAddSystemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSystemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddSystemeActionPerformed

    private void jToggleButtonAddImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAddImageActionPerformed
        this.jScrollPaneImage.setVisible(false);
        this.jPanelAddImage.setVisible(true);
    }//GEN-LAST:event_jToggleButtonAddImageActionPerformed

    private void jButtonAnnulerImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerImageActionPerformed
        this.jPanelAddImage.setVisible(false);
        this.jScrollPaneImage.setVisible(true);
    }//GEN-LAST:event_jButtonAnnulerImageActionPerformed

    private void jButtonSaveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveImageActionPerformed
        String nom = this.jTextFieldNomI.getText();
        String date = this.jTextFieldDateI.getText();
        String description = this.jTextAreaDescriptionI.getText();
        String urlI = this.jTextFieldUrlI.getText();
       // int id = ProjetBDM.getId("image");
        
        Image img = new Image();
        img.insererImage(1, nom, date, description, urlI);
    }//GEN-LAST:event_jButtonSaveImageActionPerformed

    private void jButtonParcourirIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcourirIActionPerformed
        JFileChooser jf=new JFileChooser();
        int i=jf.showOpenDialog(this);
        String urlI = "";
        if(i==JFileChooser.APPROVE_OPTION)
        {
            urlI = jf.getSelectedFile().toString();
        }
        this.jTextFieldUrlI.setText(urlI);
    }//GEN-LAST:event_jButtonParcourirIActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSysteme;
    private javax.swing.JButton jButtonAnnulerImage;
    private javax.swing.JButton jButtonParcourirI;
    private javax.swing.JButton jButtonSaveImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelErrSysteme;
    private javax.swing.JLabel jLabelSuccSysteme;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelAddImage;
    private javax.swing.JPanel jPanelSysteme;
    private javax.swing.JPanel jPanelUtilisateur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneImage;
    private javax.swing.JTabbedPane jTabbedPaneImage;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDescriptionI;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldDateI;
    private javax.swing.JTextField jTextFieldNomI;
    private javax.swing.JTextField jTextFieldUrlI;
    private javax.swing.JToggleButton jToggleButtonAddImage;
    // End of variables declaration//GEN-END:variables
}
