/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.io.File;
import java.io.IOException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;
import oracle.ord.im.OrdImage;
import oracle.sql.REF;
import oracle.sql.STRUCT;
import projetbdm.Miniature;
import projetbdm.ProjetBDM;
import projetbdm.Thesaurus;

/**
 *
 * @author cmolin
 */
public class Window extends javax.swing.JFrame {
    
    //contient la connexion a la base de donné faite dans projetBDM
    private final Connection con;
    //liste contenant toutes les miniature à afficher
    ArrayList<Miniature> trouve = new ArrayList();
            
    /**
     * Creates new form Window
     */
    public Window(Connection con) {
        this.con = con;
        initComponents();
        this.setVisible(true);
        this.setTitle("Le monde des applications");
        jPanelAcceuil.setVisible(true);
        jPanelAffiche.setVisible(false);
        jPanelLogAdmin.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanelLogAdmin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonAdmin = new javax.swing.JButton();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jComboBoxCategorie = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jButtonVCategorie = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxSysteme = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButtonVSysteme = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxRech = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldMotRech = new javax.swing.JTextField();
        jButtonLanceRechMot = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldThes = new javax.swing.JTextField();
        jComboBoxThes = new javax.swing.JComboBox();
        jButtonValiderThes = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jButtonLanceRechCompa = new javax.swing.JButton();
        jButtonParcourir = new javax.swing.JButton();
        jTextFieldRechImage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSlidercouleur = new javax.swing.JSlider();
        jSliderforme = new javax.swing.JSlider();
        jSlidertexture = new javax.swing.JSlider();
        jSliderlocalisation = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldseuil = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButtonAfficheAdmin = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanelAcceuil = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanelAffiche = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(230, 230, 230));
        jPanel1.setMinimumSize(new java.awt.Dimension(210, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(210, 700));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanelLogAdmin.setBackground(new java.awt.Color(230, 230, 230));
        jPanelLogAdmin.setPreferredSize(new java.awt.Dimension(189, 100));
        jPanelLogAdmin.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelLogAdmin.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanelLogAdmin.add(jLabel4, gridBagConstraints);

        jTextFieldLogin.setMaximumSize(new java.awt.Dimension(200, 28));
        jTextFieldLogin.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextFieldLogin.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelLogAdmin.add(jTextFieldLogin, gridBagConstraints);

        jButtonAdmin.setText("Go");
        jButtonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdminActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanelLogAdmin.add(jButtonAdmin, gridBagConstraints);

        jPasswordFieldPassword.setMaximumSize(new java.awt.Dimension(200, 28));
        jPasswordFieldPassword.setMinimumSize(new java.awt.Dimension(200, 28));
        jPasswordFieldPassword.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanelLogAdmin.add(jPasswordFieldPassword, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(230, 230, 230));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jComboBoxCategorie.setMaximumSize(new java.awt.Dimension(200, 28));
        jComboBoxCategorie.setMinimumSize(new java.awt.Dimension(200, 28));
        jComboBoxCategorie.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel2.add(jComboBoxCategorie, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Recherche par catégorie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel2.add(jLabel6, gridBagConstraints);

        jButtonVCategorie.setText("Valider");
        jButtonVCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVCategorieActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel2.add(jButtonVCategorie, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(230, 230, 230));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 5, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);

        jComboBoxSysteme.setMaximumSize(new java.awt.Dimension(200, 28));
        jComboBoxSysteme.setMinimumSize(new java.awt.Dimension(200, 28));
        jComboBoxSysteme.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jPanel3.add(jComboBoxSysteme, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Recherche par système");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel3.add(jLabel8, gridBagConstraints);

        jButtonVSysteme.setText("Valider");
        jButtonVSysteme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVSystemeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel3.add(jButtonVSysteme, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(230, 230, 230));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel4.setLayout(jPanel4Layout);

        jComboBoxRech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toutes les images", "Dans image", "Dans image (nom)", "Dans image (description)", "Dans application", "Dans application (nom)", "Dans application (description)" }));
        jComboBoxRech.setMaximumSize(new java.awt.Dimension(200, 28));
        jComboBoxRech.setMinimumSize(new java.awt.Dimension(200, 28));
        jComboBoxRech.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jComboBoxRech, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Recherche par mots-clés");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel4.add(jLabel1, gridBagConstraints);

        jTextFieldMotRech.setMaximumSize(new java.awt.Dimension(200, 28));
        jTextFieldMotRech.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextFieldMotRech.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jTextFieldMotRech, gridBagConstraints);

        jButtonLanceRechMot.setText("Valider");
        jButtonLanceRechMot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLanceRechMotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jButtonLanceRechMot, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(230, 230, 230));
        java.awt.GridBagLayout jPanel5Layout = new java.awt.GridBagLayout();
        jPanel5Layout.columnWidths = new int[] {0, 5, 0};
        jPanel5Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel5.setLayout(jPanel5Layout);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Recherche sur application");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jLabel7, gridBagConstraints);

        jTextFieldThes.setMaximumSize(new java.awt.Dimension(200, 28));
        jTextFieldThes.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextFieldThes.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jTextFieldThes, gridBagConstraints);

        jComboBoxThes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BT", "NT", "RT", "SYN" }));
        jComboBoxThes.setMaximumSize(new java.awt.Dimension(200, 28));
        jComboBoxThes.setMinimumSize(new java.awt.Dimension(200, 28));
        jComboBoxThes.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel5.add(jComboBoxThes, gridBagConstraints);

        jButtonValiderThes.setText("Valider");
        jButtonValiderThes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderThesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jButtonValiderThes, gridBagConstraints);

        jLabel9.setText("(Thesaurus)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel5.add(jLabel9, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(230, 230, 230));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel6Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel6.setLayout(jPanel6Layout);

        jButtonLanceRechCompa.setText("Lancer");
        jButtonLanceRechCompa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLanceRechCompaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        jPanel6.add(jButtonLanceRechCompa, gridBagConstraints);

        jButtonParcourir.setText("Parcourir");
        jButtonParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParcourirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        jPanel6.add(jButtonParcourir, gridBagConstraints);

        jTextFieldRechImage.setMaximumSize(new java.awt.Dimension(200, 28));
        jTextFieldRechImage.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextFieldRechImage.setPreferredSize(new java.awt.Dimension(200, 28));
        jTextFieldRechImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRechImageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        jPanel6.add(jTextFieldRechImage, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Recherche suivant une image");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel6.add(jLabel2, gridBagConstraints);

        jSlidercouleur.setPreferredSize(new java.awt.Dimension(206, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        jPanel6.add(jSlidercouleur, gridBagConstraints);

        jSliderforme.setPreferredSize(new java.awt.Dimension(206, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        jPanel6.add(jSliderforme, gridBagConstraints);

        jSlidertexture.setPreferredSize(new java.awt.Dimension(206, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        jPanel6.add(jSlidertexture, gridBagConstraints);

        jSliderlocalisation.setMaximumSize(new java.awt.Dimension(32767, 40));
        jSliderlocalisation.setPreferredSize(new java.awt.Dimension(206, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        jPanel6.add(jSliderlocalisation, gridBagConstraints);

        jLabel10.setText("Couleur");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel6.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Forme");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        jPanel6.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Texture");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        jPanel6.add(jLabel12, gridBagConstraints);

        jLabel13.setText("Localisation");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        jPanel6.add(jLabel13, gridBagConstraints);

        jTextFieldseuil.setText("50");
        jTextFieldseuil.setMinimumSize(new java.awt.Dimension(6, 28));
        jTextFieldseuil.setPreferredSize(new java.awt.Dimension(30, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel6.add(jTextFieldseuil, gridBagConstraints);

        jLabel14.setText("Seuil :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        jPanel6.add(jLabel14, gridBagConstraints);

        jButtonAfficheAdmin.setText("Administrateur");
        jButtonAfficheAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAfficheAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButtonAfficheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelLogAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAfficheAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelLogAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setLayout(new java.awt.CardLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel5.setText("Page d'acceuil");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel15.setText("Bienvenue");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel16.setText("Le monde");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 55)); // NOI18N
        jLabel17.setText("Applications");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel18.setText("Sur");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel19.setText("Des");

        javax.swing.GroupLayout jPanelAcceuilLayout = new javax.swing.GroupLayout(jPanelAcceuil);
        jPanelAcceuil.setLayout(jPanelAcceuilLayout);
        jPanelAcceuilLayout.setHorizontalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)))
                            .addComponent(jLabel17)))
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel18))
                    .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel19)))
                .addContainerGap(235, Short.MAX_VALUE))
        );
        jPanelAcceuilLayout.setVerticalGroup(
            jPanelAcceuilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAcceuilLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        jPanel7.add(jPanelAcceuil, "card5");

        jPanelAffiche.setBorder(javax.swing.BorderFactory.createTitledBorder("Résultat de la recherche"));
        jPanelAffiche.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanelAfficheComponentResized(evt);
            }
        });

        jPanel9.setMaximumSize(new java.awt.Dimension(150, 200));
        jPanel9.setMinimumSize(new java.awt.Dimension(150, 200));
        jPanel9.setPreferredSize(new java.awt.Dimension(150, 200));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelAfficheLayout = new javax.swing.GroupLayout(jPanelAffiche);
        jPanelAffiche.setLayout(jPanelAfficheLayout);
        jPanelAfficheLayout.setHorizontalGroup(
            jPanelAfficheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAfficheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(588, Short.MAX_VALUE))
        );
        jPanelAfficheLayout.setVerticalGroup(
            jPanelAfficheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAfficheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(540, Short.MAX_VALUE))
        );

        jPanel7.add(jPanelAffiche, "card4");

        jMenuBar1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jMenuBar1ComponentRemoved(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Acceuil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Actualiser Index");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setText("Quitter");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //fait le traitement suivant la recherche par mot demande dans la jcombobox correspondante
    void foncRecherche(String choix)
    {
        //reinitialise trouve
        trouve = new ArrayList();
        try
        {
            Statement s=con.createStatement();
            String mot = jTextFieldMotRech.getText();
            OracleResultSet rset;
            switch(choix)
            {
                case "Toutes les images" :
                    //affiche toutes les images sans exception
                    rset = (OracleResultSet)s.executeQuery("select miniature, idI, nomI from image");
                    while(rset.next())
                    {
                        OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                        int nume = rset.getInt(2);
                        String nome = rset.getString(3);
                        String num2 = Integer.toString(nume);
                        String url ;
                        if(minia.getContentLength() == 0) url = "rien.png";
                        else 
                        {
                            url = "image/miniature-"+num2+nome+".jpeg";
                            minia.getDataInFile(url);
                        }
                        Miniature mimimini = new Miniature(nume, url, nome, "", con);
                        //ajout à la liste à afficher
                        trouve.add(mimimini);
                    }
                    rset.close();
                    break;
                case "Dans image" : 
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select miniature, idI, nomI "
                            + "from image "
                            + "where contains (nomI,'"+ chaine[1] +"')>0 "
                            + "or contains (descriptionI,'!"+ chaine[1] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select miniature, idI, nomI "
                                + "from image "
                                + "where contains (nomI,'"+ chaine[0] +"')>0 "
                                + "or contains (descriptionI,'!"+ chaine[0] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }

                        while(rset.next())
                        {
                            OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                            int nume = rset.getInt(2);
                            String nome = rset.getString(3);
                            String num2 = Integer.toString(nume);
                            String url ;
                            if(minia.getContentLength() == 0) url = "rien.png";
                            else 
                            {
                                url = "image/miniature-"+num2+nome+".jpeg";
                                minia.getDataInFile(url);
                            }
                            Miniature mimimini = new Miniature(nume, url, nome, "", con);
                            //ajout à la liste à afficher
                            trouve.add(mimimini);
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                case "Dans image (nom)" : 
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select miniature, idI, nomI "
                            + "from image "
                            + "where contains (nomI,'"+ chaine[1] +"')>0 ", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select miniature, idI, nomI "
                                + "from image "
                                + "where contains (nomI,'"+ chaine[0] +"')>0 ", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }
                        
                        while(rset.next())
                        {
                            OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                            int nume = rset.getInt(2);
                            String nome = rset.getString(3);
                            String num2 = Integer.toString(nume);
                            String url ;
                            if(minia.getContentLength() == 0) url = "rien.png";
                            else 
                            {
                                url = "image/miniature-"+num2+nome+".jpeg";
                                minia.getDataInFile(url);
                            }
                            Miniature mimimini = new Miniature(nume, url, nome, "", con);
                            //ajout à la liste à afficher
                            trouve.add(mimimini);
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                case "Dans image (description)" : 
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select miniature, idI, nomI "
                            + "from image "
                            + "where contains (descriptionI,'"+ chaine[1] +"')>0 ", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select miniature, idI, nomI "
                                + "from image "
                                + "where contains (descriptionI,'"+ chaine[0] +"')>0 ", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }
                        
                        while(rset.next())
                        {
                            OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                            int nume = rset.getInt(2);
                            String nome = rset.getString(3);
                            String num2 = Integer.toString(nume);
                            String url ;
                            if(minia.getContentLength() == 0) url = "rien.png";
                            else 
                            {
                                url = "image/miniature-"+num2+nome+".jpeg";
                                minia.getDataInFile(url);
                            }
                            Miniature mimimini = new Miniature(nume, url, nome, "", con);
                            //ajout à la liste à afficher
                            trouve.add(mimimini);
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                case "Dans application" :
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select a.idA "
                            + "from application a "
                            + "where contains (nomA,'"+ chaine[1] +"')>0 "
                            + "or contains (descriptionA,'!"+ chaine[1] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select a.idA "
                                + "from application a "
                                + "where contains (nomA,'"+ chaine[0] +"')>0 "
                                + "or contains (descriptionA,'!"+ chaine[0] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                                OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }
                        
                        while(rset.next())
                        {
                            int numnum = rset.getInt(1);
                            OracleResultSet rset2 = (OracleResultSet)s.executeQuery(
                                "select miniature, idI, nomI "
                                        + "from image i "
                                        + "where i.applicationI.idA = "+numnum+" ");
                            while(rset2.next())
                            {
                                OrdImage minia = (OrdImage) rset2.getORAData(1,OrdImage.getORADataFactory());
                                int nume = rset2.getInt(2);
                                String nome = rset2.getString(3);
                                String num2 = Integer.toString(nume);
                                String url ;
                                if(minia.getContentLength() == 0) url = "rien.png";
                                else 
                                {
                                    url = "image/miniature-"+num2+nome+".jpeg";
                                    minia.getDataInFile(url);
                                }
                                Miniature mimimini = new Miniature(nume, url, nome, "", con);
                                //ajout à la liste à afficher
                                trouve.add(mimimini);
                            }
                            rset2.close();
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                case "Dans application (nom)" :
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select a.idA "
                            + "from application a "
                            + "where contains (nomA,'"+ chaine[1] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select a.idA "
                                + "from application a "
                                + "where contains (nomA,'"+ chaine[0] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                                OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }

                        while(rset.next())
                        {
                            int numnum = rset.getInt(1);
                            OracleResultSet rset2 = (OracleResultSet)s.executeQuery(
                                "select miniature, idI, nomI "
                                        + "from image i "
                                        + "where i.applicationI.idA = "+numnum+" ");
                            while(rset2.next())
                            {
                                OrdImage minia = (OrdImage) rset2.getORAData(1,OrdImage.getORADataFactory());
                                int nume = rset2.getInt(2);
                                String nome = rset2.getString(3);
                                String num2 = Integer.toString(nume);
                                String url ;
                                if(minia.getContentLength() == 0) url = "rien.png";
                                else 
                                {
                                    url = "image/miniature-"+num2+nome+".jpeg";
                                    minia.getDataInFile(url);
                                }
                                Miniature mimimini = new Miniature(nume, url, nome, "", con);
                                //ajout à la liste à afficher
                                trouve.add(mimimini);
                            }
                            rset2.close();
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                case "Dans application (description)" :
                    if(!"".equals(mot))
                    {
                        String[] chaine = this.prepareRequeteRech(mot);
                        //AND si plus de 3 résultats et OR dans le cas contraire
                        PreparedStatement st = con.prepareStatement("select a.idA "
                            + "from application a "
                            + "where contains (descriptionA,'"+ chaine[1] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                            OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                        rset = (OracleResultSet) st.executeQuery();
                        if (this.getRowCount(rset) < 3) {
                            st = con.prepareStatement("select a.idA "
                                + "from application a "
                                + "where contains (descriptionA,'"+ chaine[0] +"')>0", OracleResultSet.TYPE_SCROLL_INSENSITIVE, OracleResultSet.CONCUR_UPDATABLE,
                                OracleResultSet.HOLD_CURSORS_OVER_COMMIT);
                            rset = (OracleResultSet) st.executeQuery();
                        }

                        while(rset.next())
                        {
                            int numnum = rset.getInt(1);
                            OracleResultSet rset2 = (OracleResultSet)s.executeQuery(
                                "select miniature, idI, nomI "
                                        + "from image i "
                                        + "where i.applicationI.idA = "+numnum+" ");
                            while(rset2.next())
                            {
                                OrdImage minia = (OrdImage) rset2.getORAData(1,OrdImage.getORADataFactory());
                                int nume = rset2.getInt(2);
                                String nome = rset2.getString(3);
                                String num2 = Integer.toString(nume);
                                String url ;
                                if(minia.getContentLength() == 0) url = "rien.png";
                                else 
                                {
                                    url = "image/miniature-"+num2+nome+".jpeg";
                                    minia.getDataInFile(url);
                                }
                                Miniature mimimini = new Miniature(nume, url, nome, "", con);
                                //ajout à la liste à afficher
                                trouve.add(mimimini);
                            }
                            rset2.close();
                        }
                        rset.close();
                    }
                    else
                    {
                        //si le champs est vide on met un msg d'erreur
                        JLabel jj = new JLabel("Pas de résultat pour votre recherche");
                        jj.setBounds(20, 20, 500, 15);
                        jPanelAffiche.add(jj);
                    }
                    break;
                default :
                    System.out.println("erreur combo box");
                    break;
            }
            s.close();
        }catch(Exception e){e.printStackTrace();}
        //lance l'affichage des miniatures
        this.remplirPanelAffiche(trouve);
    }
    
    private String[] prepareRequeteRech(String chaine) throws SQLException
    {
        String[] parts = chaine.split(" ");
        String[] chaineR = new String[2];
        chaineR[0] = "!" + parts[0];
        chaineR[1] = "!" + parts[0];
        for (int i=1; i < parts.length; i++)
        {
            chaineR[0] += " OR !" + parts[i];
            chaineR[1] += " AND !" + parts[i];
        }
        
        return chaineR;
    }
    
    private int getRowCount(OracleResultSet resultSet) {
        if (resultSet == null) {
            return 0;
        }
        try {
            resultSet.last();
            return resultSet.getRow();
        } catch (SQLException exp) {
            exp.printStackTrace();
        } finally {
            try {
                resultSet.beforeFirst();
            } catch (SQLException exp) {
                exp.printStackTrace();
            }
       }
       return 0;
    }
    
    //affiche les miniatures dans le panel prévu pour cela
    public void remplirPanelAffiche(ArrayList<Miniature> trouve)
    {
        //initialise le panel
        jPanelAffiche.removeAll();
        jPanelAffiche.repaint();
        if(trouve.isEmpty())
        {
            //si l'attribut est vide on met un msg d'erreur
            JLabel jj = new JLabel("Pas de résultat pour votre recherche");
            jj.setBounds(20, 20, 500, 15);
            jPanelAffiche.add(jj);
        }
        else
        {
            //on va placer les miniatures par rapport à la taille du panel
            int abscisse = 20;
            int ordonne = 10;
            int largueur = jPanelAffiche.getSize().width;
            int cmp = 0;
            int cmpMax = largueur/200;
            for(Miniature mimi : trouve)
            {
                //creation de la miniature a l'endroit donné par ordonne et abscisse
                mimi.afficheMini(jPanelAffiche, ordonne, abscisse);
                cmp++;
                if(cmp<cmpMax)
                {
                    ordonne += 200;
                }
                else
                {
                    abscisse += 200;
                    ordonne = 10;
                    cmp = 0;
                }
            }
        }
    }
    
    //ouvre l'acceuil quand on clique sur acceuil dans le menu
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jPanelAcceuil.setVisible(true);        
        jPanelAffiche.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //ferme l'application quand on clique sur quitter dans le menu
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    //réaffiche quand la taille du panel change
    private void jPanelAfficheComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanelAfficheComponentResized
        this.remplirPanelAffiche(trouve);
    }//GEN-LAST:event_jPanelAfficheComponentResized

    //ouvre le jfilechooser quand on clique sur parcourir
    private void jButtonParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParcourirActionPerformed
        JFileChooser jf=new JFileChooser();
        String image_chargement = "";
        int i=jf.showOpenDialog(this);
        if(i==JFileChooser.APPROVE_OPTION)
        {
            image_chargement=jf.getSelectedFile().getAbsolutePath();
        }
        jTextFieldRechImage.setText(image_chargement);
    }//GEN-LAST:event_jButtonParcourirActionPerformed

    private void jTextFieldRechImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRechImageActionPerformed

    }//GEN-LAST:event_jTextFieldRechImageActionPerformed

    //ouvre la fenetre administrateur si le login/mdp est bon
    private void jButtonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdminActionPerformed
        WindowAdmin wa;
        String login = this.jTextFieldLogin.getText();
        String password = new String(this.jPasswordFieldPassword.getPassword());
        if (!ProjetBDM.uConnexion(login, password)) {
            System.out.println("Erreur login/mot de passe");
        } else {
            wa = new WindowAdmin(this.con);
            wa.setVisible(true);
        }
    }//GEN-LAST:event_jButtonAdminActionPerformed

    //affiche le panel avec le login et mdp
    private void jButtonAfficheAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAfficheAdminActionPerformed
        if(jPanelLogAdmin.isVisible() == false) jPanelLogAdmin.setVisible(true);
        else jPanelLogAdmin.setVisible(false);
    }//GEN-LAST:event_jButtonAfficheAdminActionPerformed
    
    //on ajoute l'image a comparer en id 0 puis on la compare avec tte les image de la base
    private void jButtonLanceRechCompaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLanceRechCompaActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelAffiche.setVisible(true);
        trouve = new ArrayList();
        String image_chargement = "";
        int seuil = 50;
        if(!"".equals(jTextFieldseuil.getText()))
            seuil = Integer.parseInt(jTextFieldseuil.getText());
        image_chargement = jTextFieldRechImage.getText();
        double couleur = (double)jSlidercouleur.getValue()/100;
        double forme = (double)jSliderforme.getValue()/100;
        double localisation = (double)jSliderlocalisation.getValue()/100;
        double texture = (double)jSlidertexture.getValue()/100;
        if(!"".equals(image_chargement))
        {
            try
            {
                Statement stmt = con.createStatement();
                //vérif que l'image id=0 existe
                OracleResultSet rset = (OracleResultSet) stmt.executeQuery("select count(idI) from image where idI=0");
                if(rset.next())
                {
                    int existe = rset.getInt(1);
                    //si non on l'insert
                    if(existe == 0)
                    {
                        PreparedStatement pstmt = con.prepareStatement("INSERT INTO image VALUES (0,to_date(?, 'DD/MM/YYYY')"
                            + ",'image a comparer','image a comparer', ordsys.ordimage.init(), ordsys.ordimage.init(), null)");
                        pstmt.setString(1, "06/05/2014");
                        pstmt.executeQuery();
                        con.commit();
                        pstmt.close();
                    }
                }     
                rset.close();
                // insertion de l'image a comparer en id 0
                OracleResultSet rset2 = (OracleResultSet) stmt.executeQuery("select imageI, miniature from image where idI=0 for update");
                if(rset2.next())
                {
                    OrdImage img = (OrdImage) rset2.getORAData(1, OrdImage.getORADataFactory());
                    OrdImage miniature = (OrdImage) rset2.getORAData(2, OrdImage.getORADataFactory());
                    img.loadDataFromFile(image_chargement);
                    img.processCopy("MaxScale=150 150", miniature);
                    img.setProperties();
                    miniature.setProperties();
                    //Mise à jour de l'attribut image
                    OraclePreparedStatement pstmt = (OraclePreparedStatement) con.prepareStatement("update "
                            + "image set imageI = ? where idI=0");
                    pstmt.setORAData(1, img);
                    pstmt.execute();
                    con.commit();
                    pstmt.close();
                    //Mise à jour de l'attribut miniature
                    OraclePreparedStatement pstmt2 = (OraclePreparedStatement) con.prepareStatement("update "
                            + "image set miniature = ? where idI=0");
                    pstmt2.setORAData(1, miniature);
                    pstmt2.execute();
                    con.commit();
                    pstmt2.close();
                }
                rset2.close();
                //on récup les images de la base avec leur score calculé par compare
                OracleResultSet rset3 = (OracleResultSet) stmt.executeQuery("select i.miniature,i.idI,i.nomI, i.compare("+couleur+","+forme+","+localisation+","+texture+") from image i");
                while(rset3.next())
                {
                    OrdImage minia = (OrdImage) rset3.getORAData(1,OrdImage.getORADataFactory());
                    int nume = rset3.getInt(2);
                    String nome = rset3.getString(3);
                    double score = rset3.getDouble(4);
                    //si le score est concluant on l'ajoute
                    if(score < seuil)
                    {
                        String num2 = Integer.toString(nume);
                        String url ;
                        if(minia.getContentLength() == 0) url = "rien.png";
                        else 
                        {
                            url = "image/miniature-"+num2+nome+".jpeg";
                            minia.getDataInFile(url);
                        }
                        Miniature mimimini = new Miniature(nume, url, nome, Double.toString(score) , con);
                        trouve.add(mimimini);
                    }                                
                }
                rset3.close();
                stmt.close();
            }catch(Exception e){e.printStackTrace();}
        }
        else
        {
            JLabel jj = new JLabel("Vous n'avez pas rentré d'image");
            jj.setBounds(20, 20, 500, 15);
            jPanelAffiche.add(jj);
        }
        //on affiche le résultat
        this.remplirPanelAffiche(trouve);
    }//GEN-LAST:event_jButtonLanceRechCompaActionPerformed
    
    //initialise et appel le traitement pour la recherche par mot
    private void jButtonLanceRechMotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLanceRechMotActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelAffiche.setVisible(true);
        trouve.clear();
        jPanelAffiche.removeAll();
        jPanelAffiche.repaint();
        String indic = (String)jComboBoxRech.getSelectedItem();
        this.foncRecherche(indic);
    }//GEN-LAST:event_jButtonLanceRechMotActionPerformed

    //rempli les combobox à l'ouverture de la fenetre
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //Sélection des catégories
        try {
            //Sélection des catégories
            PreparedStatement st;
            st = con.prepareStatement("select * from categorie");
            st.executeQuery();
            ResultSet rst = st.executeQuery();
            while (rst.next()) {
                this.jComboBoxCategorie.addItem(rst.getString(2));
            }
        }
        catch(Exception e) {System.out.println(e);}
        
        //Sélection des systèmes
        try {
            //Sélection des systèmes
            PreparedStatement st;
            st = con.prepareStatement("select * from systeme");
            st.executeQuery();
            ResultSet rst = st.executeQuery();
            while (rst.next()) {
                this.jComboBoxSysteme.addItem(rst.getString(1));
            }
        }
        catch(Exception e) {System.out.println(e);}
    }//GEN-LAST:event_formComponentShown

    //affiche les images des applications appartenant à la catégorie sélectionné
    private void jButtonVCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVCategorieActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelAffiche.setVisible(true);
        trouve.clear();
        jPanelAffiche.removeAll();
        jPanelAffiche.repaint();
        PreparedStatement st;
        String idC = this.jComboBoxCategorie.getSelectedItem().toString();
        try {
            st = con.prepareStatement("select value(a) from application a "
                    + "where a.categorieA = (select ref(c) from categorie c where c.nomC = ?)");
            st.setString(1, idC);
            OracleResultSet rsetA = (OracleResultSet) st.executeQuery();
            while(rsetA.next()) {
                STRUCT str = (STRUCT) rsetA.getSTRUCT(1);
                Object[] tabAtt = str.getAttributes();

                Array arI = (Array) tabAtt[7];
                OracleResultSet rsetI = (OracleResultSet) arI.getResultSet();
                while (rsetI.next())
                {
                    STRUCT strI = rsetI.getSTRUCT(2);
                    Object[] tabAttI = strI.getAttributes();
                    REF refI = (REF) tabAttI[0];
                    STRUCT strI2 = refI.getSTRUCT();
                    Object[] tabI2 = strI2.getAttributes();
                    System.out.println(tabI2[0]);
                    st = con.prepareStatement("select miniature, idI, nomI from image where idI = " + tabI2[0]);
                    OracleResultSet rset = (OracleResultSet)st.executeQuery();
                    rset.next();
                    OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                    int nume = rset.getInt(2);
                    String nome = rset.getString(3);
                    String num2 = Integer.toString(nume);
                    String url ;
                    if(minia.getContentLength() == 0) url = "rien.png";
                    else 
                    {
                        url = "image/miniature-"+num2+nome+".jpeg";
                        try {
                            minia.getDataInFile(url);
                        } catch (IOException ex) {
                            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    Miniature mimimini = new Miniature(nume, url, nome, "", con);
                    trouve.add(mimimini);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.remplirPanelAffiche(trouve);
    }//GEN-LAST:event_jButtonVCategorieActionPerformed

    //affiche la recherche avec le thesaurus
    private void jButtonValiderThesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderThesActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelAffiche.setVisible(true);
        trouve.clear();
        jPanelAffiche.removeAll();
        jPanelAffiche.repaint();
        String mot = this.jTextFieldThes.getText();
        String rel = this.jComboBoxThes.getSelectedItem().toString();
        if (!"".equals(mot)) {
            Thesaurus thes = new Thesaurus("app_thes");
            OracleResultSet rset1 = thes.rechercheThes(mot, rel);
            PreparedStatement st;
            try {
                while(rset1.next()) {
                    STRUCT str = (STRUCT) rset1.getSTRUCT(1);
                    Object[] tabAtt = str.getAttributes();

                    Array arI = (Array) tabAtt[7];
                    OracleResultSet rsetI = (OracleResultSet) arI.getResultSet();
                    while (rsetI.next())
                    {
                        STRUCT strI = rsetI.getSTRUCT(2);
                        Object[] tabAttI = strI.getAttributes();
                        REF refI = (REF) tabAttI[0];
                        STRUCT strI2 = refI.getSTRUCT();
                        Object[] tabI2 = strI2.getAttributes();
                        System.out.println(tabI2[0]);
                        st = con.prepareStatement("select miniature, idI, nomI from image where idI = " + tabI2[0]);
                        OracleResultSet rset = (OracleResultSet)st.executeQuery();
                        rset.next();
                        OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                        int nume = rset.getInt(2);
                        String nome = rset.getString(3);
                        String num2 = Integer.toString(nume);
                        String url ;
                        if(minia.getContentLength() == 0) url = "rien.png";
                        else
                        {
                            url = "image/miniature-"+num2+nome+".jpeg";
                            try {
                                minia.getDataInFile(url);
                            } catch (IOException ex) {
                                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        Miniature mimimini = new Miniature(nume, url, nome, "", con);
                        trouve.add(mimimini);
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.remplirPanelAffiche(trouve);
        }
        else {
            JOptionPane.showMessageDialog(this, "Remplir le champ");
        }
    }//GEN-LAST:event_jButtonValiderThesActionPerformed

    //affiche les images des apllications ayant pour systeme celui selectionné
    private void jButtonVSystemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVSystemeActionPerformed
        jPanelAcceuil.setVisible(false);
        jPanelAffiche.setVisible(true);
        trouve.clear();
        jPanelAffiche.removeAll();
        jPanelAffiche.repaint();
        PreparedStatement st;
        String nomS = this.jComboBoxSysteme.getSelectedItem().toString();
        try {
            st = con.prepareStatement("select value(a) from applicationSysteme a where "
                    + "a.systemeA = (select ref(s) from systeme s where s.nomS = ?)");
            st.setString(1, nomS);
            OracleResultSet rset1 = (OracleResultSet) st.executeQuery();
            while (rset1.next())
            {
                STRUCT str1 = (STRUCT) rset1.getSTRUCT(1);
                Object[] tabAtt1 = str1.getAttributes();
                REF ref1 = (REF) tabAtt1[1];
                STRUCT str2 = ref1.getSTRUCT();
                Object[] tabAtt2 = str2.getAttributes();
                Array ar1 = (Array) tabAtt2[7];
                OracleResultSet rset2 = (OracleResultSet) ar1.getResultSet();
                while (rset2.next())
                {
                    STRUCT strI = rset2.getSTRUCT(2);
                    Object[] tabAtt3 = strI.getAttributes();
                    REF ref2 = (REF) tabAtt3[0];
                    STRUCT str3 = ref2.getSTRUCT();
                    Object[] tabAtt4 = str3.getAttributes();
                    System.out.println(tabAtt4[0]);
                    st = con.prepareStatement("select miniature, idI, nomI from image where idI = " + tabAtt4[0]);
                    OracleResultSet rset = (OracleResultSet)st.executeQuery();
                    rset.next();
                    OrdImage minia = (OrdImage) rset.getORAData(1,OrdImage.getORADataFactory());
                    int nume = rset.getInt(2);
                    String nome = rset.getString(3);
                    String num2 = Integer.toString(nume);
                    String url ;
                    if(minia.getContentLength() == 0) url = "rien.png";
                    else
                    {
                        url = "image/miniature-"+num2+nome+".jpeg";
                        try {
                            minia.getDataInFile(url);
                        } catch (IOException ex) {
                            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    Miniature mimimini = new Miniature(nume, url, nome, "", con);
                    trouve.add(mimimini);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.remplirPanelAffiche(trouve);
    }//GEN-LAST:event_jButtonVSystemeActionPerformed

    //reconstruit les index quand on clique dans le menu sur actualiser index
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        PreparedStatement st;
        try {
            st = con.prepareStatement("alter index nomIindex rebuild");
            st.execute();
            st = con.prepareStatement("alter index descriptionIindex rebuild");
            st.execute();
            st = con.prepareStatement("alter index nomAindex rebuild");
            st.execute();
            st = con.prepareStatement("alter index descriptionAindex rebuild");
            st.execute();
            con.commit();
            st.close();
        } catch (SQLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuBar1ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1ComponentRemoved

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("testttt");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.out.println("test");
        File myDir = new File("image");
        emptyDirectory(myDir);
    }
    
        
    public void emptyDirectory(File folder){
        for(File file : folder.listFiles()){
            if(file.isDirectory()){
                emptyDirectory(file);
            }
            file.delete();
        }
    }//GEN-LAST:event_formWindowClosing

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdmin;
    private javax.swing.JButton jButtonAfficheAdmin;
    private javax.swing.JButton jButtonLanceRechCompa;
    private javax.swing.JButton jButtonLanceRechMot;
    private javax.swing.JButton jButtonParcourir;
    private javax.swing.JButton jButtonVCategorie;
    private javax.swing.JButton jButtonVSysteme;
    private javax.swing.JButton jButtonValiderThes;
    private javax.swing.JComboBox jComboBoxCategorie;
    private javax.swing.JComboBox jComboBoxRech;
    private javax.swing.JComboBox jComboBoxSysteme;
    private javax.swing.JComboBox jComboBoxThes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAcceuil;
    private javax.swing.JPanel jPanelAffiche;
    private javax.swing.JPanel jPanelLogAdmin;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSlider jSlidercouleur;
    private javax.swing.JSlider jSliderforme;
    private javax.swing.JSlider jSliderlocalisation;
    private javax.swing.JSlider jSlidertexture;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldMotRech;
    private javax.swing.JTextField jTextFieldRechImage;
    private javax.swing.JTextField jTextFieldThes;
    private javax.swing.JTextField jTextFieldseuil;
    // End of variables declaration//GEN-END:variables
}
