/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaces;

import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleResultSet;
import oracle.ord.im.OrdImage;

/**
 *
 * @author Rémus
 */
public class WindowAffiche extends javax.swing.JFrame {
    int identifiant;
    private final Connection con;
    Image img;
    JPanel paner;
    /**
     * Creates new form WindowAffiche
     */
    public WindowAffiche(Connection c, int m, String g) {
        initComponents();
        this.identifiant = m;
        this.con = c;
        this.setTitle(g);
        this.setVisible(true);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.remplirTout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelImage = new javax.swing.JPanel();
        jPanelAttribut = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAttribut = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 400));

        jPanelImage.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 91));

        jTableAttribut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Attributs de l'image", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAttribut);

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        javax.swing.GroupLayout jPanelAttributLayout = new javax.swing.GroupLayout(jPanelAttribut);
        jPanelAttribut.setLayout(jPanelAttributLayout);
        jPanelAttributLayout.setHorizontalGroup(
            jPanelAttributLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanelAttributLayout.setVerticalGroup(
            jPanelAttributLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAttributLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAttribut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
            .addComponent(jPanelAttribut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void afficheImage(JPanel pan,Image img)
    {
        Graphics g=pan.getGraphics();
        
        int widthPanel = this.jPanelImage.getWidth();
        int heightPanel = this.jPanelImage.getHeight();
        
        float coef = this.coefImage(widthPanel, heightPanel, img.getWidth(null), img.getHeight(null));
        
        int x = (int) (img.getWidth(null) * coef);
        int y = (int) (img.getHeight(null) * coef);
        
        int posx = (widthPanel - img.getWidth(null)) / 2;
        int posy = (heightPanel - img.getHeight(null)) / 2;
        
        if (posx < 0) posx = 0;
        if (posy < 0) posy = 0;
        
        g.drawImage(img, posx, posy, x, y,this);
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        if(img!=null)
            afficheImage(paner,img);
    }
    
    public void remplirTout()
    {
        try
        {
            //récup de l'image dans la base
            Statement s = con.createStatement();
            String idI = Integer.toString(identifiant);
            String info = "";
            OracleResultSet rset = (OracleResultSet)s.executeQuery(
                    "select imageI, nomI, dateI, descriptionI, "
                            + "i.applicationI.nomA, i.applicationI.descriptionA, i.applicationI.version "
                            + "from image i "
                            + "where i.idI="+idI);
            if(rset.next())
            {
                OrdImage im=(OrdImage)rset.getORAData(1, OrdImage.getORADataFactory());
                String nomI = rset.getString(2);
                String urlFich = idI+nomI+".jpeg";
                String date = rset.getString(3);
                String descripI = rset.getString(4);
                String nomA = rset.getString(5);
                String descripA = rset.getString(6);
                String versionA = rset.getString(7);
                info = info+"Information sur l'image :\n nom : "+nomI+"\n date : "+date+"\n description : "+descripI+"\n\n";
                String info2 = "Information sur l'application :\n nom : "+nomA+"\n description : "+descripA+"\n version : "+versionA;
                info = info+info2;
                jTextArea.setText(info);
                im.getDataInFile(urlFich);
                DefaultTableModel dtm = (DefaultTableModel) this.jTableAttribut.getModel();
                dtm.addRow(new Object[]{"hauteur",im.getHeight()});
                dtm.addRow(new Object[]{"Largeur",im.getWidth()});
                dtm.addRow(new Object[]{"Taille",im.getContentLength()});
                dtm.addRow(new Object[]{"Format",im.getFormat()});
                img = jPanelImage.getToolkit().getImage(urlFich);
                paner = jPanelImage;
                repaint();
            }
            rset.close();
            s.close();
        }catch(Exception e){e.printStackTrace();} 
    }
    
    private float coefImage(int widthPanel, int heightPanel, int widthImg, int heightImg)
    {
        float coef = 1;
        
        int ratioWidth = widthImg - widthPanel;
        int ratioHeight = heightImg - heightPanel;
        
        if (ratioWidth > ratioHeight) {
            if (widthImg > widthPanel) coef = (float) widthPanel / widthImg;
        }
        else {
            if (heightImg > heightPanel) coef = (float) heightPanel / heightImg; 
        } 
        
        return coef;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelAttribut;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAttribut;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables
}
